---
- name: Install openssh (RedHat)
  when: ansible_os_family == "RedHat"
  become: yes
  yum:
    name:
      - openssh
    state: present
    update_cache: yes

- name: Install openssh (Debian)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name:
      - openssh-client
      - openssh-server
    state: present
    update_cache: yes

- name: PasswordAuthentication change no to yes
  become: yes
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '#(#|\s)*?PasswordAuthentication[\s\x20]*(yes|no)'
    replace: 'PasswordAuthentication yes'
    backup: yes
  notify: sshd restart

- name: Register sshd config file text
  when: root_login == true
  become: yes
  shell: cat /etc/ssh/sshd_config
  register: result
  changed_when: false

- name: Change PermitRootLogin no to yes
  when:
    - root_login == true
    - result.stdout | regex_search('^#?\s?PermitRootLogin\s+(?:yes|no)', multiline=True)
  become: yes
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s?PermitRootLogin\s+(?:yes|no)'
    replace: 'PermitRootLogin yes'
    backup: yes
  notify: sshd restart

- name: Add PermitRootLogin yes
  when:
    - root_login == true
    - not result.stdout | regex_search('^#?\s?PermitRootLogin\s+(?:yes|no)', multiline=True)
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    insertafter: EOF
    backup: yes
  notify: sshd restart

- name: Update /etc/hosts file
  become: yes
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'hosts.j2') }}"
    state: present
    backup: yes
    
- meta: flush_handlers

- name: make ssh connection to hosts
  include : connection.yaml