---
- name: docker group create
  group:
    name: docker
    state: present

- name: Ensure docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: generate docker config file to use systemd driver
  when: systemd_cgroup == true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: docker service start

- name: generate docker service and socket
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  with_items:
    - docker.service
    - docker.socket
  notify: docker service start

- name: add docker group on user
  user:
    name: "{{ target['user'] }}"
    groups: docker
    append: yes

- meta: flush_handlers